profiles:
    home:
        - "init.vim" :
            link: "~/.config/nvim/init.vim"
        - "init.vim" :
            link: "~/.vimrc"
        - "~/.config/nvim" :
            link: "~/.vim"
        - "hammerspoon/init.lua" :
            link: "~/.hammerspoon/init.lua"
        - "hammerspoon/watcher.lua" :
            link: "~/.hammerspoon/watcher.lua"
        - "bash_profile" :
            link: "~/.bash_profile"
        - "tmux.conf" :
            link: "~/.tmux.conf"
