config:

    home:

        link:
            - "init.vim" : "~/.config/nvim/init.vim"
            -  "~/.config/nvim/init.vim" : "~/.vimrc"
            -  "~/.config/nvim" : "~/.vim"
            - ".hammerspoon" : "~/.hammerspoon"
            - ".bash_profile" : "~/.bash_profile"
